name: scouting_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

# msix_config:
#   display_name: Scout Ops
#   publisher_display_name: FEDS201
#   identity_name: feds.suite.scoutingapp
#   msix_version: 1.0.0.0
#   capabilities: internetClient, location, microphone, webcam

environment:
  sdk: '>=3.4.3 <5.0.0'

dependencies:
  carousel_slider: ^5.0.0
  confetti: ^0.8.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.6
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  animated_text_kit: ^4.2.2
  card_swiper: ^3.0.1
  timeline_tile: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.0
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/2025/Areana2025.png
    - assets/2024/Areana2024.png
    - assets/2024/RedAlliance_2024.png
    - assets/2024/BlueAlliance_2024.png
    - assets/2024/BlueAlliance_StartPosition_2024.png
    - assets/2024/RedAlliance_StartPosition_2024.png
    - assets/2025/RedAlliance_2025.png
    - assets/2025/BlueAlliance_2025.png
    - assets/2025/BlueAlliance_StartPosition_2025.png
    - assets/2025/RedAlliance_StartPosition_2025.png
    - assets/Swerve.png
    - assets/logo.png
    - assets/logo__.png
    - assets/thumb.png
    - assets/ref/Cheat-Sheet.jpg
    - assets/ref/Cheat-Sheet-2.jpg
    - assets/Default/Auton.json
    - assets/Default/TeleOp.json
    - assets/Default/EndGame.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #     - images/a_dot_burr.jpeg
  #     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages